# Generated by Django 4.2.7 on 2023-11-06 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
